"""
Tavily API wrapper for web search.
MATCHES YOUR NOTEBOOK IMPLEMENTATION EXACTLY.
"""
from tavily import TavilyClient
from config import settings
import logging
from typing import Dict


class TavilyTool:
    """
    Wrapper for Tavily search API.
    Uses advanced AI-generated answers (not raw results).
    """
    
    def __init__(self):
        self.client = TavilyClient(api_key=settings.tavily_api_key)
        self.logger = logging.getLogger("tools.tavily")
        self.max_results = settings.tavily_max_results
        self.query_max_length = settings.tavily_query_max_length
    
    def search(self, query: str, max_results: int = None) -> Dict:
        """
        Search using Tavily with AI-generated answer.
        EXACT NOTEBOOK IMPLEMENTATION.
        
        Args:
            query: Search query (max 400 chars)
            max_results: Number of results to return (default: 5)
            
        Returns:
            Dictionary with 'answer' key containing AI-synthesized response
            
        Example:
            >>> result = tool.search("Barclays customer acquisition...")
            >>> print(result["answer"])  # Long-form AI answer
        """
        max_results = max_results or self.max_results
        
        # Truncate query if too long
        if len(query) > self.query_max_length:
            self.logger.warning(
                f"Query too long ({len(query)} chars). Truncating to {self.query_max_length}"
            )
            query = query[:self.query_max_length]
        
        self.logger.info(f"Searching: {query[:100]}...")
        
        try:
            # CRITICAL: include_answer="advanced" generates AI synthesis
            # This matches your notebook exactly
            response = self.client.search(
                query=query,
                include_answer="advanced",  # ← NOTEBOOK PARAMETER
                search_depth="advanced",
                max_results=max_results
            )
            
            # Extract the AI-generated answer (notebook approach)
            answer = response.get("answer", "")
            
            if not answer:
                self.logger.warning("No answer generated by Tavily")
            else:
                self.logger.info(f"Generated answer: {len(answer)} chars")
            
            # Return format matches notebook: {"answer": "..."}
            return {"answer": answer}
            
        except Exception as e:
            self.logger.error(f"Search failed: {str(e)}")
            raise
    
    def validate_query(self, query: str) -> tuple:
        """
        Validate query length.
        
        Args:
            query: Query to validate
            
        Returns:
            Tuple of (is_valid, truncated_query)
        """
        is_valid = len(query) <= self.query_max_length
        truncated = query[:self.query_max_length] if not is_valid else query
        
        return is_valid, truncated